@url = http://localhost:8080

###
POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "tester1",
    "password": "P@ssw0rd!"
}

###
POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "tester1",
    "password": "P@ssw0rd!!"
}

###
POST {{url}}/sighting HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJucGMiLCJzdWIiOiJ0ZXN0ZXIxIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2NjE1Mzk3MjJ9.-EgsoBh3cJhgcbzaPfKY4Euz_lWehW8uVNR3sKKu8Lw


{
  "bugType": "Mosquito",
  "order": {
    "bugOrderId": 4
  },
  "description": "annoying",
  "date": "2020-08-12",
  "interest": 0.1
}