@url = http://localhost:8080

### [ ] Successful login
POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "tester1",
    "password": "P@ssw0rd!"
}

### [ ] Unsuccessful login with wrong password
POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "tester1",
    "password": "P@ssw0rd!!"
}

### [ ] Create new account
POST {{url}}/create_account HTTP/1.1
Content-Type: application/json

{
    "username": "tester4",
    "password": "P@ssw0rd!"
}

### [ ] Create new account with bad password
### Return a 400
POST {{url}}/create_account HTTP/1.1
Content-Type: application/json

{
    "username": "tester4",
    "password": "password"
}

### [ ] Create a duplicate username
### Return a 400
POST {{url}}/create_account HTTP/1.1
Content-Type: application/json

{
    "username": "tester1",
    "password": "P@ssw0rd!"
}