@url = http://localhost:8080/api/backlog

### [ ] Find all backlogs

GET http://localhost:8080/api/backlog/user-backlog/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJucGMiLCJzdWIiOiJ0ZXN0ZXIxIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2NjE5NTk5ODV9.K2wWgp1eB70GHsnKLjo3KLjvwumYMnqR6N9OXWocbwU

### [ ] Return backlog by ID

GET http://localhost:8080/api/backlog/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJucGMiLCJzdWIiOiJ0ZXN0ZXIxIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2NjE5NTk5ODV9.K2wWgp1eB70GHsnKLjo3KLjvwumYMnqR6N9OXWocbwU

### [ ] Failed return backlog by ID
### Return a 404

GET http://localhost:8080/api/backlog/200000 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJucGMiLCJzdWIiOiJ0ZXN0ZXIxIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2NjE5NTk5ODV9.K2wWgp1eB70GHsnKLjo3KLjvwumYMnqR6N9OXWocbwU

### [ ] Post backlog

POST http://localhost:8080/api/backlog HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJucGMiLCJzdWIiOiJ0ZXN0ZXIxIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2NjE5NTk5ODV9.K2wWgp1eB70GHsnKLjo3KLjvwumYMnqR6N9OXWocbwU

{
    "userId": 3,
    "gameId": 2,
    "datetimeAdded": "2022-08-22T11:36:07.000+00:00",
    "completed": true
}

### [ ] Return 400 if user ID emty

POST http://localhost:8080/api/backlog HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJucGMiLCJzdWIiOiJ0ZXN0ZXIxIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2NjE5NTk5ODV9.K2wWgp1eB70GHsnKLjo3KLjvwumYMnqR6N9OXWocbwU

{

}

### [ ] Fail to post backlog if duplicate

POST http://localhost:8080/api/backlog HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJucGMiLCJzdWIiOiJ0ZXN0ZXIxIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2NjE5NTk5ODV9.K2wWgp1eB70GHsnKLjo3KLjvwumYMnqR6N9OXWocbwU

{
    "backlogId": 2,
    "userId": 1,
    "gameId": 1,
    "datetimeAdded": "2022-08-22T11:36:07.000+00:00",
    "completed": false
}

### [ ] Update an backlog

PUT http://localhost:8080/api/backlog/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJucGMiLCJzdWIiOiJ0ZXN0ZXIxIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2NjE5NTk5ODV9.K2wWgp1eB70GHsnKLjo3KLjvwumYMnqR6N9OXWocbwU

{
    "backlogId": 1,
    "userId": 3,
    "gameId": 3,
    "datetimeAdded": "2022-08-22T11:36:07.000+00:00",
    "completed": true
}

### [ ] 400 if empty

PUT http://localhost:8080/api/backlog/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJucGMiLCJzdWIiOiJ0ZXN0ZXIxIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2NjE5NTk5ODV9.K2wWgp1eB70GHsnKLjo3KLjvwumYMnqR6N9OXWocbwU

{
    "backlogId": 3
}

### [ ] Delete backlog by ID

DELETE http://localhost:8080/api/backlog/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJucGMiLCJzdWIiOiJ0ZXN0ZXIxIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2NjE5NTk5ODV9.K2wWgp1eB70GHsnKLjo3KLjvwumYMnqR6N9OXWocbwU

### [ ] 404 if backlog not found

DELETE http://localhost:8080/api/backlog/200000 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJucGMiLCJzdWIiOiJ0ZXN0ZXIxIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2NjE5NTk5ODV9.K2wWgp1eB70GHsnKLjo3KLjvwumYMnqR6N9OXWocbwU