@url = http://localhost:8080/api/user

# get all users

GET http://localhost:8080/api/user HTTP/1.1

### [ ] return user by id

GET http://localhost:8080/api/user/2 HTTP/1.1

### [ ] failed return user by id

GET http://localhost:8080/api/user/200000 HTTP/1.1

### [ ] post user

POST http://localhost:8080/api/user HTTP/1.1
Content-Type: application/json

{
  "userName": "TesterTest",
  "userPassword": "asfsafafasdasfassfas"
}

### [ ] return 400 duplicate user

POST http://localhost:8080/api/user HTTP/1.1
Content-Type: application/json

{
  "userName": "TesterTest",
  "userPassword": "asfsafafasdasfassfas"
}

### [ ] return 400 if name empty

POST http://localhost:8080/api/user HTTP/1.1
Content-Type: application/json

{
  "userName": "",
  "userPassword": "asfsafafasdasfassfas"
}

### [ ] return 400 if password empty

POST http://localhost:8080/api/user HTTP/1.1
Content-Type: application/json

{
  "userName": "TesterTestwrgwe",
  "userPassword": ""
}